// callsigns.js
window.WHITELIST_CALLSIGNS = new Set([
  'CFPXD','CFFIF','CFFPL','CFIRS','CFPXN','CFPXR','CFPXW','CFPXY','CFPXZ','CFZPV',
  'CGFPI','CGFPL','CGFPZ','CGJJK','CGMGZ','CGNTM','CGOSX','CGRIK','CGUHK','CGUSZ','CGZRH','CGZUE'
]);